### PR TITLE
x-checker-data: Mark eog as important

### PR DESCRIPTION
**Pull request by A6GibKm**
Only open PRs when eog is updated.

### CODE REVIEW

**Comment by alatiera** [comment]
Hmm not sure about this one, the only other modules are codec/decoders which are likely to have security releases. Will be good to have the bot tracking those too.

**Comment by TingPing** [comment]
I agree with @alatiera.

**Comment by A6GibKm** [comment]
Fair  which modules should be marked as important?

**Comment by TingPing** [comment]
`libwebp`, `libheif`, `libde265`, `jpeg-xl`,

**Comment by A6GibKm** [comment]
I updated the MR but I didn't touch `jpeg-xl` since it didn't use x-checker-data to begin with.

**Pull request merged**
