### PR TITLE
Remove libwebp

### PR DESCRIPTION
**Pull request by bbhtt**
Closes https://github.com/flathub/org.gnome.eog/issues/103

### CODE REVIEW

**Comment by TingPing** [comment]
FDO backported it I presume?

**Comment by jjardon** [comment]
> FDO backported it I presume?

It should be there since freedesktop-sdk-23.08.0 / GNOME 45.0

**Comment by bbhtt** [comment]
GNOME applied the patch on top of 22.08 in the 44.5 tag https://gitlab.gnome.org/GNOME/gnome-build-meta/-/blob/29493c1e17c3c964c0f360251923ef73c53de282/elements/freedesktop-sdk.bst#L9

44 received an update today so I assume that was it.

**Comment by bbhtt** [comment]
Also yea, it was backported on FDO 22.08 too https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/merge_requests/15003 but looks like it didn't make into a release yet

**Pull request merged**
